apiVersion: apps/v1
kind: Deployment
metadata:
  name: azuresql
  labels:
    app: azuresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azuresql
  template:
    metadata:
      labels:
        app: azuresql
    spec:
      containers:
        - name: azuresql
          image: binarymisfit/azure-edge
          ports:
            - containerPort: 1433
      imagePullSecrets:
        - name: binaryhub