apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlmaster
spec:
  capacity:
    storage: 5G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
    name: sqlmaster-claim
  local:
    path: /opt/kubernetes/volumes/sqlmaster
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop