version: "3.9"
services:
  sonarr:
    build:
      context: sonarr
    container_name: sonarr
    init: true
    pid: "host"
    restart: unless-stopped
    networks:
      - services_connect
      - services_exposed

networks:
  services_connect:
    name: services
  services_exposed:
    name: expose
    driver: host
