version: "3.9"
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    hostname: watchtower
    environment:
      - "TZ=Africa/Johannesburg"
      - "WATCHTOWER_CLEANUP=true"
      - "WATCHTOWER_REMOVE_VOLUMES=true"
      - "WATCHTOWER_HTTP_API_METRICS=true"
      - "WATCHTOWER_ROLLING_RESTART=true"
      - "WATCHTOWER_HTTP_API_TOKEN=e152e78c-b8b7-43d0-8c20-7bee1a5d81d7"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  elastic:
    image: elasticsearch:7.14.2
    container_name: elastic
    hostname: elastic
    environment:
      - "TZ=Africa/Johannesburg"
      - "discovery-type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      - watchtower
  kabana:
    image: kibana:7.14.2
    container_name: kibana
    hostname: kibana
    environment:
      - "TZ=Africa/Johannesburg"
    ports:
      - "5601:5601"
    links:
      - elastic:elasticsearch
    depends_on:
      - elastic
