version: "3.9"
services:
  elastic:
    image: elasticsearch:7.14.2
    container_name: elastic
    hostname: elastic
    environment:
      - "discovery-type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
