#!/usr/bin/env bash

if [[ -f "${HOME}/.dotfiles/default/scripts/shared/bmfunc.sh" ]]; then
  source "${HOME}/.dotfiles/default/scripts/shared/bmfunc.sh"
  if [[ -n "${BM_LOADED+x}" ]]; then
    bm_init
  else
    printf "\r\033[0;91m[FAILED]\033[0;97m Shared functions not loaded\033[0m\n"
    exit 255
  fi
else
  printf "\r\033[0;91m[FAILED]\033[0;97m Shared functions not found\033[0m\n"
  exit 255
fi

bm_print_title "Ubuntu configurator V1.0.0"
bm_user_no_sudo
bm_print_info "User: ${BM_USER}"
bm_print_info "Home: ${HOME}"
bm_print_info "Sudo: ${BM_USE_SUDO}"
bm_print_info "Script path: $0"
bm_command_locate add-apt-repository
bm_command_locate md5sum
bm_task_start "Configuring environment"
if [[ ! -d "${HOME}/.npm_global" ]]; then
  bm_task_update "Configuring environment"
  bm_make_dir "${HOME}/.npm_global"
fi

bm_task_ok "Configuring environment"
bm_task_start "Checking nodesource"
if [[ "${BM_USE_SUDO}" == "1" ]]; then
  DISTRO="$(lsb_release -s -c)"
  FILE_CONTENT="\
  deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x $DISTRO main
  deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x $DISTRO main"
  if [[ -f /etc/apt/sources.list.d/nodesource.list ]]; then
    MD5_CURRENT=$(md5sum /etc/apt/sources.list.d/nodesource.list | awk '{ print $1 }')
    MD5_NEW=$(printf "%s" "${FILE_CONTENT}" | md5sum | awk '{ print $1 }')
    if [[ "${MD5_CURRENT}" != "${MD5_NEW}" ]]; then
      bm_task_update "Checking nodesource"
      curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor |
        sudo tee /usr/share/keyrings/nodesource.gpg >/dev/null
      printf "%s" "${FILE_CONTENT}" | sudo tee /etc/apt/sources.list.d/nodesource.list >/dev/null
      bm_task_ok "Checking nodesource"
      bm_print_info "Version C: ${MD5_CURRENT}"
      bm_print_info "Version N: ${MD5_NEW}"
      bm_task_start "Updating apt"
      if ! bm_command_execute "sudo apt-get update"; then
        bm_task_failed "Updating apt"
        bm_command_output_error
        bm_script_error
      fi

      bm_task_ok "Updating apt"
      bm_command_output_success
    else
      bm_task_ok "Checking nodesource"
    fi

    unset DISTRO
    unset MD5_CURRENT
    unset MD5_NEW
  fi

  if [[ ! -f /etc/apt/sources.list.d/nodesource.list ]]; then
    bm_task_update "Checking nodesource"
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor |
      sudo tee -a /usr/share/keyrings/nodesource.gpg >/dev/null
    printf "%s" "${FILE_CONTENT}" | sudo tee -a /etc/apt/sources.list.d/nodesource.list >/dev/null
    bm_task_ok "Checking nodesource"
    bm_task_start "Updating apt"
    if ! bm_command_execute "sudo apt-get update"; then
      bm_task_failed "Updating apt"
      bm_command_output_error
      bm_script_error
    fi

    bm_task_ok "Updating apt"
    bm_command_output_success
  fi
else
  bm_task_skip "Checking nodesource"
fi

bm_task_start "Checking git ppa"
if [[ "${BM_USE_SUDO}" == "1" ]]; then
  bm_task_update "Checking git ppa"
  if [[ "$(grep -l git-core /etc/apt/sources.list.d/*)" == "" ]]; then
    if ! bm_command_execute "sudo add-apt-repository -nsy ppa:git-core/ppa"; then
      bm_task_failed "Checking git ppa"
      bm_command_output_error
      bm_script_error
    fi

    bm_task_ok "Checking git ppa"
    bm_command_output_success
    bm_task_start "Updating apt"
    if ! bm_command_execute "sudo apt-get update"; then
      bm_task_failed "Updating apt"
      bm_command_output_error
      bm_script_error
    fi

    bm_task_ok "Updating apt"
    bm_command_output_success
  else
    bm_task_ok "Checking git ppa"
  fi
else
  bm_task_skip "Checking git ppa"
fi

bm_task_start "Checking neovim unstable"
if [[ "${BM_USE_SUDO}" == "1" ]]; then
  bm_task_update "Checking neovim unstable"
  if [[ "$(grep -l neovim-ppa/unstable /etc/apt/sources.list.d/*)" == "" ]]; then
    if ! bm_command_execute "sudo add-apt-repository -nsy ppa:neovim-ppa/unstable"; then
      bm_task_failed "Checking neovim unstable"
      bm_command_output_error
      bm_script_error
    fi

    bm_task_ok "Checking neovim unstable"
    bm_command_output_success
    bm_task_start "Updating apt"
    if ! bm_command_execute "sudo apt-get update"; then
      bm_task_failed "Updating apt"
      bm_command_output_error
      bm_script_error
    fi

    bm_task_ok "Updating apt"
    bm_command_output_success
  else
    bm_task_ok "Checking neovim unstable"
  fi
else
  bm_task_skip "Checking neovim unstable"
fi

bm_task_start "Checking required apps"
INSTALL_LIST=()
if [[ "${BM_USE_SUDO}" == "1" ]]; then
  if ! bm_ubuntu_package_installed build-essential; then
    INSTALL_LIST+=("build-essential")
  fi

  if ! bm_ubuntu_package_installed coreutils; then
    INSTALL_LIST+=("coreutils")
  fi

  if ! bm_command_check cron; then
    INSTALL_LIST+=("cron")
  fi

  if ! bm_command_check curl; then
    INSTALL_LIST+=("curl")
  fi

  if ! bm_command_check neofetch; then
    INSTALL_LIST+=("neofetch")
  fi

  if ! bm_command_check node; then
    INSTALL_LIST+=("nodejs")
  fi

  if ! bm_command_check nvim; then
    INSTALL_LIST+=("neovim")
  fi

  if ! bm_command_check python3; then
    install_list+=("python3")
  fi

  if ! bm_command_check pip; then
    install_list+=("python3-pip")

  if ! bm_command_check socat; then
    INSTALL_LIST+=("socat")
  fi

  if ! bm_command_check tmux; then
    INSTALL_LIST+=("tmux")
  fi

  if ! bm_command_check zsh; then
    INSTALL_LIST+=("zsh")
  fi

  if [[ ! -f /usr/share/zsh-antigen/antigen.zsh ]]; then
    INSTALL_LIST+=("zsh-antigen")
  fi

  if [[ ${#INSTALL_LIST[@]} -eq 0 ]]; then
    bm_task_ok "Checking required apps"
  else
    bm_task_update "Checking required apps"
    for APP in "${INSTALL_LIST[@]}"; do
      bm_print_info "Missing: ${APP}"
    done
  fi
else
  bm_task_skip "Checking required apps"
fi

if [[ "${BM_USE_SUDO}" == "1" ]]; then
  bm_ubuntu_update_check
  bm_task_start "Installing ubuntu updates"
  if [[ "${BM_OS_UPDATE}" == "1" ]]; then
    bm_task_update "Installing ubuntu updates"
    if ! bm_command_execute "sudo apt-get update"; then
      bm_task_failed "Installing ubuntu updates"
      bm_command_output_error
      bm_script_error
    fi

    if ! bm_command_execute "sudo apt-get upgrade --yes"; then
      bm_task_failed "Installing ubuntu updates"
      bm_command_output_error
      bm_script_error
    fi

    bm_task_ok "Installing ubuntu updates"
    bm_command_output_success
    bm_task_start "Cleaning ubuntu apps"
    if ! bm_command_execute "sudo apt-get autoremove --yes"; then
      bm_task_failed "Cleaning ubuntu apps"
      bm_command_output_error
      bm_script_error
    fi

    bm_task_ok "Cleaning ubuntu apps"
    bm_command_output_success
  else
    bm_task_skip "Installing ubuntu updates"
  fi
fi

if [[ "${BM_USE_SUDO}" == "1" ]]; then
  bm_task_start "Installing missing apps"
  if [[ ${#INSTALL_LIST[@]} -ne 0 ]]; then
    bm_task_update "Installing missing apps"
    if ! bm_command_execute "sudo apt-get update"; then
      bm_task_failed "Installing missing apps"
      bm_command_output_error
      bm_script_error
    fi

    ARGS=$(printf "%s " "${INSTALL_LIST[@]}")
    if ! bm_command_execute "sudo apt-get install --yes ${ARGS}"; then
      bm_task_failed "Installing missing apps"
      bm_command_output_error
      bm_script_error
    fi

    bm_task_ok "Installing missing apps"
    bm_command_output_success
    unset ARGS
    bm_task_start "Cleaning ubuntu apps"
    if ! bm_command_execute "sudo apt-get autoremove --yes"; then
      bm_task_failed "Cleaning ubuntu apps"
      bm_command_output_error
      bm_script_error
    fi

    bm_task_ok "Cleaning ubuntu apps"
    bm_command_output_success
  else
    bm_task_skip "Installing missing apps"
  fi
fi

unset INSTALL_LIST
INSTALL_LIST=()

if [[ "${BM_USE_SUDO}" == "1" ]]; then
  bm_task_start "Removing obsolete apps"
  if ! bm_ubuntu_package_installed vim; then
    INSTALL_LIST+=("vim")
  fi

  if ! bm_ubuntu_package_installed vim-tiny; then
    INSTALL_LIST+=("vim-tiny")
  fi

  if [[ ${#INSTALL_LIST[@]} -gt 0 ]]; then
    bm_task_update "Removing obsolete apps"
    if ! bm_command_execute "apt-get ${ARGS_APT} remove --purge -y ${INSTALL_LIST[*]}"; then
      bm_task_failed "Removing obsolete apps"
      bm_command_output_error
      bm_script_error
    fi

    if [[ "${VERBOSE}" == "1" ]]; then
      printf "\033[0;34mRunning apt-get autoremove\033[0m\n"
    fi

    bm_task_ok "Removing obsolete apps"
    bm_command_output_success
    for APP in "${INSTALL_LIST[@]}"; do
      bm_print_info "Removing: ${APP}"
    done

    bm_task_start "Cleaning ubuntu apps"
    if ! bm_command_execute "sudo apt-get autoremove --yes"; then
      bm_task_failed "Cleaning ubuntu apps"
      bm_command_output_error
      bm_script_error
    fi
  else
    bm_task_skip "Removing obsolete apps"
  fi
fi

unset INSTALL_LIST

bm_task_start "Checking neovim"
OUTPUT=$(bm_command_exit_code "npm -g list neovim")
if [[ ${OUTPUT} -eq 1 ]]; then
  bm_task_update "Checking neovim"
  if ! bm_command_execute "npm -g install neovim@latest"; then
    bm_task_failed "Checking neovim"
    bm_command_output_error
  fi

  bm_task_ok "Checking neovim"
  bm_print_info "npm exit ${OUTPUT}"
  bm_command_output_success
else
  bm_task_ok "Checking neovim"
  bm_print_info "npm exit ${OUTPUT}"
fi

unset OUTPUT

bm_task_start "Checking pip"
if [[ "${BM_USE_SUDO}" == "1" ]]; then
  if ! bm_command_check pip; then
    bm_task_update "Checking pip"
    if ! bm_command_execute "curl -fL https://bootstrap.pypa.io/get-pip.py | python3 -"; then
      bm_task_failed "Checking pip"
      bm_command_output_error
    fi

    bm_task_ok "Checking pip"
    bm_command_output_success
    bm_task_start "Updating pip"
    bm_task_update "Updating pip"
    if ! bm_command_execute "python3 -m pip install --upgrade pip"; then
      bm_task_failed "Updating pip"
      bm_command_output_error
    fi

    bm_task_ok "Updating pip"
    bm_command_output_success
  else
    bm_task_ok "Checking pip"
  fi
else
  bm_task_skip "Checking pip"
fi

if [[ "${BM_USE_SUDO}" == "1" ]]; then
  bm_task_start "Checking pynvim"
  OUTPUT=$(bm_command_exit_code "python3 -m pip list | grep pynvim")
  if [[ ${OUTPUT} -ne 0 ]]; then
    bm_task_update "Checking pynvim"
    if ! bm_command_execute "python3 -m pip install --upgrade pynvim"; then
      bm_task_failed "Checking pynvim"
      bm_command_output_error
    fi

    bm_task_ok "Checking pynvim"
    bm_print_info "python exit ${OUTPUT}"
    bm_command_output_success
  else
    bm_task_ok "Checking pynvim"
    bm_print_info "python exit ${OUTPUT}"
  fi
else
  bm_task_skip "Checking pynvim"
fi

if [[ "${BM_USE_SUDO}" == "1" ]]; then
  bm_task_start "Checking sudo config"
  if [[ -f /etc/sudoers.d/90-cloud-init-users ]]; then
    rm /etc/sudoers.d/90-cloud-init-users
  fi

  FILE_CONTENT="Defaults env_keep += ""TMUX"""
  if [[ -f /etc/sudoers.d/50-keep-environment ]]; then
    MD5_CURRENT=$(md5sum </etc/sudoers.d/50-keep-environment | awk '{ print $1 }')
    MD5_NEW=$(printf "%s" "${FILE_CONTENT}" | md5sum | awk '{ print $1 }')
    if [[ "${MD5_CURRENT}" != "${MD5_NEW}" ]]; then
      bm_task_update "Checking sudo config"
      printf "%s" "${FILE_CONTENT}" | sudo tee /etc/sudoers.d/50-keep-environment >/dev/null
      bm_task_ok "Checking sudo config"
    else
      bm_task_ok "Checking sudo config"
    fi

    bm_print_info "Version C: ${MD5_CURRENT}"
    bm_print_info "Version N: ${MD5_NEW}"
  else
    bm_task_update "Checking sudo config"
    printf "%s" "${FILE_CONTENT}" | sudo tee /etc/sudoers.d/50-keep-environment >/dev/null
    bm_task_ok "Checking sudo config"
  fi
else
  bm_task_skip "Checking sudo config"
fi

if [[ "${BM_USE_SUDO}" == "1" ]]; then
  bm_task_start "Checking ${BM_USER} shell"
  ZSH_PATH=$(which zsh)
  if [[ "${ZSH_PATH}" != "$(getent passwd "${BM_USER}" | awk -F: '{print $NF}')" ]]; then
    bm_task_update "Checking ${BM_USER} shell"
    if ! bm_command_execute "sudo chsh ${BM_USER} --shell ${ZSH_PATH}"; then
      bm_task_failed "Checking ${BM_USER} shell"
      bm_command_output_error
    fi

    bm_task_ok "Checking ${BM_USER} shell"
    bm_command_output_success
  else
    bm_task_ok "Checking ${BM_USER} shell"
  fi

  unset ZSH_PATH
else
  bm_task_skip "Checking ${BM_USER} shell"
fi

bm_task_start "Checking Neovim"
NVIM_PATH=$(which nvim)
if [[ "${NVIM_PATH}" != "$(update-alternatives --get-selections | grep 'editor' | awk '{ print $3 }')" ]]; then
  bm_task_update "Checking Neovim"
  OUTPUT=$(bm_command_exit_code "update-alternatives --display vi")
  if [[ ${OUTPUT} -eq 1 ]]; then
    if ! bm_command_execute "update-alternatives --install /usr/bin/vi vi ${NVIM_PATH} 100"; then
      bm_task_failed "Checking Neovim"
      bm_command_output_error
    fi
  fi

  unset OUTPUT
  OUTPUT=$(bm_command_exit_code "update-alternatives --display editor")
  if [[ ${OUTPUT} -eq 1 ]]; then
    if ! bm_command_execute "update-alternatives --install /usr/bin/editor editor ${NVIM_PATH} 100"; then
      bm_task_failed "Checking Neovim"
      bm_command_output_error
    fi
  fi

  unset OUTPUT
  if ! bm_command_execute "update-alternatives --set editor ${NVIM_PATH}"; then
    bm_task_failed "Checking Neovim"
    bm_command_output_error
  fi

  bm_command_output_success

  if ! bm_command_execute "update-alternatives --set vi ${NVIM_PATH}"; then
    bm_task_failed "Checking Neovim"
    bm_command_output_error
  fi

  bm_task_ok "Checking Neovim"
  bm_command_output_success
else
  bm_task_ok "Checking Neovim"
fi

unset NVIM_PATH

bm_script_error

if [[ "${SUDO}" == "1" ]] && [[ "${SUDO_USER}" != "" ]]; then
  FILE_CONTENT="\
  #!/bin/bash
  \nneofetch --config /etc/neofetch/config.conf\n"
  if [[ -f /etc/update-motd.d/01-neofetch ]]; then
    MD5_CURRENT=$(md5sum /etc/update-motd.d/01-neofetch | awk '{ print $1 }')
    MD5_NEW=$(printf "%s" "${FILE_CONTENT}" | md5sum | awk '{ print $1 }')
    if [[ "${MD5_CURRENT}" != "${MD5_NEW}" ]]; then
      if [[ "${VERBOSE}" == "1" ]]; then
        printf "\033[0;34mUpdating sudo environment\033[0m\n"
        printf "\033[0;31mMD5 Mismatch ${MD5_CURRENT}/${MD5_NEW}\033[0m\n"
      fi

      printf "%s" "${FILE_CONTENT}" | sudo tee /etc/update-motd.d/01-neofetch >/dev/null
    fi
  else
    if [[ "${VERBOSE}" == "1" ]]; then
      printf "\033[0;34mUpdating sudo environment\033[0m\n"
    fi

    printf "%s" "${FILE_CONTENT}" | sudo tee /etc/update-motd.d/01-neofetch >/dev/null
  fi

  if [[ -d "/home/${SUDO_USER}/.dotfiles/default/etc/neofetch" ]]; then
    cp -R "/home/${SUDO_USER}/.dotfiles/default/etc/neofetch" /etc
  fi

  chmod -R 444 /etc/update-motd.d/*
  chmod -R 555 /etc/update-motd.d/01-neofetch
  chmod -R 555 /etc/update-motd.d/9?-*
fi

if [[ "${VERBOSE}" != "-1" ]]; then
  if [[ "${SUDO}" == "1" ]]; then
    printf "\033[0;32mAll commands have been executed\033[0m\n"
  fi

  printf "\033[0;32m\n==> All tasks executed successfully\033[0m\n"
fi
