---
- defaults:
    link:
      create: true
      relink: true
- clean:
    - "${HOME}"
- create:
    - ${HOME}/.npm_global
- shell:
    - - git pull --all
      - Updating
- link:
    ~/.config/nvim:
      path: default/nvim
    ~/.iterm2_shell_integration.zsh:
      path: default/scripts/shell/.iterm2_shell_integration.zsh
    ~/.oh-my-zsh:
      path: external/oh-my-zsh
    ~/.scripts:
      path: default/scripts/tools
    ~/.scripts/antigen.zsh:
      path: external/antigen/antigen.zsh
