---
- shell:
    -
      command: git pull --all
      description: Updating configuration files
      quiet: true
    -
      command: test -d ~/.npm_global || mkdir -p ~/.npm_global
      description: Creating Node Repo
      quiet: true
- link:
    ~/.config/nvim:
      path: default/nvim
    ~/.iterm2_shell_integration.zsh:
      path: default/scripts/shell/.iterm2_shell_integration.zsh
    ~/.scripts:
      path: default/scripts/tools
    ~/.scripts/antigen.zsh:
      path: external/antigen/antigen.zsh
