---
- defaults:
  link:
    create: true
    relink: true
- clean:
  - "${HOME}"
- link:
    ~/.antigenrc:
      path: platform/ubuntu/zsh/.antigenrc
    ~/.gitconfig:
      path: platform/ubuntu/git/.gitconfig
    ~/.npmrc:
      path: platform/ubuntu/node/.npmrc
    ~/.p10k.zsh:
      path: platform/ubuntu/zsh/.p10k.zsh
    ~/.packages:
      path: platform/ubuntu/packages
    ~/.papercolor.tmux.conf:
      path: platform/ubuntu/tmux/.papercolor.tmux.conf
    ~/.ssh/config:
      path: platform/ubuntu/ssh/config
    ~/.tmux.conf:
      path: platform/ubuntu/tmux/.tmux.conf
    ~/.zshrc:
      path: platform/ubuntu/zsh/.zshrc
