#!/usr/bin/env bash
if [[ "$EUID" -ne "0" ]]; then
  printf "\033[0;31mScript needs to be run as root, aborting\033[0m\n"
  exit 1
fi

if [[ -d /tmp/acme ]]; then
  rm -rf /tmp/acme
fi

git clone --quiet --depth 1 https://github.com/acmesh-official/acme.sh.git /tmp/acme
if [[ ! -d /tmp/acme ]] || [[ ! -x /tmp/acme/acme.sh ]]; then
  printf "\033[0;31macme.sh not found, aborting\033[0m\n"
  exit 1
fi

pushd /tmp/acme > /dev/null || exit 1
bash << EOF
  ./acme.sh \
  --install \
  --no-profile \
  --home /opt/acme \
  --config-home /etc/acme \
  --cert-home /etc/ssl/private/acme \
  --accountemail administrator@senselesslyfoolish.com \
  --accountkey /etc/acme/senselessly_foolish_account.key \
  --accountconf /etc/acme/senselessly_foolish_account.conf
EOF
bash << EOF
  ./acme.sh --upgrade --auto-upgrade --quiet
EOF
popd > /dev/null || return
rm -rf /tmp/acme
