#!/usr/bin/env bash
usage()
{
    echo "usage: showlog --host [host] --service [service]"
}

if [ "$1" == "" ]; then
    usage
    exit 1
fi

HOST=
SERVICE=
while [ "$1" != "" ]; do
    case $1 in
        --host )    shift
                    HOST=$1
                    ;;
        --service ) shift
                    SERVICE=$1
                    ;;
    esac
    shift
done

ssh -T ${HOST} << EOF
    docker logs ${SERVICE} --follow
EOF