#!/usr/bin/env bash
echo "Updating Mini"
STOP_WATCHTOWER="docker stop watchtower && docker rm watchtower"
PULL_WATCHTOWER="docker pull binarymisfit/watchtower:latest"
START_WATCHTOWER="start-watchtower.sh"
CONTAINER_PATH=/Volumes/Scratch/apps/containers/mini/
ssh -T mini << EOF
    ${STOP_WATCHTOWER}
    ${PULL_WATCHTOWER}
    ${CONTAINER_PATH}${START_WATCHTOWER}
EOF

echo "Updating Scratch"
CONTAINER_PATH=/home/willie/.source/repos/docker/containers/scratch/
ssh -T scratch << EOF
    ${STOP_WATCHTOWER}
    ${PULL_WATCHTOWER}
    ${CONTAINER_PATH}${START_WATCHTOWER}
EOF

echo "Updating Staging"
CONTAINER_PATH=/mnt/datastore/source/containers/staging/
ssh -T staging << EOF
    ${STOP_WATCHTOWER}
    ${PULL_WATCHTOWER}
    ${CONTAINER_PATH}${START_WATCHTOWER}
EOF

echo "Updating Hosting"
CONTAINER_PATH=/mnt/datastore/source/containers/hosting/
ssh -T staging << EOF
    ${STOP_WATCHTOWER}
    ${PULL_WATCHTOWER}
    ${CONTAINER_PATH}${START_WATCHTOWER}
EOF