#!/usr/bin/env bash
echo "Updating Mini"
GIT_PULL="git pull"
CONTAINER_PATH=/Volumes/Scratch/apps/containers/
ssh -T mini << EOF
    cd ${CONTAINER_PATH}
    ${GIT_PULL}
    cd
EOF

echo "Updating Scratch"
CONTAINER_PATH=/home/willie/.source/repos/docker/containers/
ssh -T scratch << EOF
    cd ${CONTAINER_PATH}
    ${GIT_PULL}
    cd
EOF

echo "Updating Staging"
CONTAINER_PATH=/mnt/datastore/source/containers/
ssh -T staging << EOF
    cd ${CONTAINER_PATH}
    ${GIT_PULL}
    cd
EOF

echo "Updating Hosting"
CONTAINER_PATH=/mnt/datastore/source/containers/
ssh -T staging << EOF
    cd ${CONTAINER_PATH}
    ${GIT_PULL}
    cd
EOF