#!/usr/bin/env bash
echo "Updating Mini"
STOP_LETSENCRYPT="docker stop letsencrypt && docker rm letsencrypt"
PULL_LETSENCRYPT="docker pull binarymisfit/letsencrypt:latest"
START_LETSENCRYPT="start-letsencrypt.sh"
CONTAINER_PATH=/Volumes/Scratch/apps/containers/mini/
ssh -T mini << EOF
    ${STOP_LETSENCRYPT}
    ${PULL_LETSENCRYPT}
    ${CONTAINER_PATH}${START_LETSENCRYPT}
EOF

echo "Updating Scratch"
CONTAINER_PATH=/home/willie/.source/repos/docker/containers/scratch/
ssh -T scratch << EOF
    ${STOP_LETSENCRYPT}
    ${PULL_LETSENCRYPT}
    ${CONTAINER_PATH}${START_LETSENCRYPT}
EOF

echo "Updating Staging"
CONTAINER_PATH=/mnt/datastore/source/containers/staging/
ssh -T staging << EOF
    ${STOP_LETSENCRYPT}
    ${PULL_LETSENCRYPT}
    ${CONTAINER_PATH}${START_LETSENCRYPT}
EOF

echo "Updating Hosting"
CONTAINER_PATH=/mnt/datastore/source/containers/hosting/
ssh -T hosting << EOF
    ${STOP_LETSENCRYPT}
    ${PULL_LETSENCRYPT}
    ${CONTAINER_PATH}${START_LETSENCRYPT}
EOF