#!/usr/bin/env bash
echo "Updating Mini"
STOP_NZBHYDRA2="docker stop nzbhydra2 && docker rm nzbhydra2"
PULL_NZBHYDRA2="docker pull binarymisfit/nzbhydra2:latest"
START_NZBHYDRA2="start-nzbhydra2.sh"
CONTAINER_PATH=/Volumes/Scratch/apps/containers/mini/
ssh -T mini << EOF
    ${STOP_NZBHYDRA2}
    ${PULL_NZBHYDRA2}
    ${CONTAINER_PATH}${START_NZBHYDRA2}
EOF

echo "Updating Scratch"
CONTAINER_PATH=/home/willie/.source/repos/docker/containers/scratch/
ssh -T scratch << EOF
    ${STOP_NZBHYDRA2}
    ${PULL_NZBHYDRA2}
    ${CONTAINER_PATH}${START_NZBHYDRA2}
EOF