#!/usr/bin/env bash
if [[ -f "${HOME}/.scripts/shared/bmfunc.sh" ]]; then
  source "${HOME}/.scripts/shared/bmfunc.sh"
  if [[ -n "${BM_LOADED+x}" ]]; then
    bm_init
  else
    printf "\r\033[0;91m[FAILED]\033[0;90m Shared functions not loaded\033[0m\n"
    exit 255
  fi
else
  printf "\r\033[0;91m[FAILED]\033[0;90m Shared functions not found\033[0m\n"
  exit 255
fi

if [[ $(bm_command_check jq) -ne 0 ]]; then
  bm_script_error "jq command not found"
fi

if [[ ! -f "${HOME}/.config/dynamic_dns/domains.conf" ]]; then
  bm_script_error "domains.conf not found"
fi

if [[ ! -f "${HOME}/.config/dynamic_dns/config.conf" ]]; then
  bm_script_error "config.conf not found"
fi

bm_print_title "Dynamic DNS Update V1.0.0"
bm_user_no_sudo
bm_task_start "Configuring environment"
CONFIG_FILE="${HOME}/.config/dynamic_dns/config.conf"
DOMAIN_FILE="${HOME}/.config/dynamic_dns/domains.conf"
DOMAINS=()
# shellcheck source=.config/config.conf
source "${CONFIG_FILE}"

bm_task_ok "Configuring environment"
bm_task_start "Loading domains"
while IFS= read -r DOMAIN; do DOMAINS+=("${DOMAIN}"); done <"${DOMAIN_FILE}"
bm_task_ok "Loading domains"
bm_task_start "Local IPv4 address"
API_URL="https://api.ipify.org"
API_RESPONSE=$(curl -s "${API_URL}")
if [[ "${API_RESPONSE}" != "" ]]; then
  USE_IP4="${API_RESPONSE}"
  bm_task_ok "Local IPv4 address"
else
  bm_task_error "Local IPv4 address"
  bm_script_error
fi

bm_task_start "Local IPv6 address"
API_URL="https://api64.ipify.org"
API_RESPONSE=$(curl -s "${API_URL}")
if [[ "${API_RESPONSE}" != "" ]]; then
  USE_IP6="${API_RESPONSE}"
  bm_task_ok "Local IPv6 address"
else
  bm_task_error "Local IPv6 address"
  bm_script_error
fi

for DOMAIN in "${DOMAINS[@]}"; do
  bm_task_start "IPv4 ${DOMAIN}"
  HOST="$(echo "${DOMAIN}" | cut -d . -f 1)"
  PARENT="$(echo "${DOMAIN}" | rev | cut -d . -f 1,2 | rev)"
  API_URL="https://api.cloudns.net/dns/records.json"
  API_REQUEST="\
  {
    \"sub-auth-id\": \"${CLOUDNS_SUB_AUTH_ID}\",
    \"auth-password\": \"${CLOUDNS_AUTH_PASSWORD}\",
    \"domain-name\": \"${PARENT}\",
    \"host\": \"${HOST}\",
    \"type\": \"A\"
  }"
  API_RESPONSE=$(curl -s --request POST -H "Content-Type:application/json" "${API_URL}" --data "${API_REQUEST}")
  DOMAIN_ID=$(jq -r '.[] .id' <<<"${API_RESPONSE}")
  DOMAIN_IP=$(jq -r '.[] .record' <<<"${API_RESPONSE}")
  if [[ "${DOMAIN_ID}" == "" ]]; then
    bm_task_failed "IPv4 ${DOMAIN}"
  elif [[ "${USE_IP4}" == "${DOMAIN_IP}" ]]; then
    bm_task_skip "IPv4 ${DOMAIN}"
  else
    API_URL="https://api.cloudns.net/dns/get-dynamic-url.json"
    API_REQUEST="\
    {
      \"sub-auth-id\": \"${CLOUDNS_SUB_AUTH_ID}\",
      \"auth-password\": \"${CLOUDNS_AUTH_PASSWORD}\",
      \"domain-name\": \"${PARENT}\",
      \"record-id\": \"${DOMAIN_ID}\"
    }"
    API_RESPONSE=$(curl -s --request POST -H "Content-Type:application/json" "${API_URL}" --data "${API_REQUEST}")
    UPDATE_URL=$(jq -r '.url' <<<"${API_RESPONSE}")
    if [[ "${UPDATE_URL}" != "" ]]; then
      bm_task_update "IPv4 ${DOMAIN}"
      if ! bm_command_execute "curl -s ${UPDATE_URL}"; then
        bm_task_failed "IPv4 ${DOMAIN}"
      else
        bm_task_ok "IPv6 ${DOMAIN}"
      fi
    else
      bm_task_failed "IPv4 ${DOMAIN}"
    fi

  fi

  unset DOMAIN_ID
  unset DOMAIN_IP
  bm_task_start "IPv6 ${DOMAIN}"
  API_URL="https://api.cloudns.net/dns/records.json"
  API_REQUEST="\
  {
    \"sub-auth-id\": \"${CLOUDNS_SUB_AUTH_ID}\",
    \"auth-password\": \"${CLOUDNS_AUTH_PASSWORD}\",
    \"domain-name\": \"${PARENT}\",
    \"host\": \"${HOST}\",
    \"type\": \"AAAA\"
  }"
  API_RESPONSE=$(curl -s --request POST -H "Content-Type:application/json" "${API_URL}" --data "${API_REQUEST}")
  DOMAIN_ID=$(jq -r '.[] .id' <<<"${API_RESPONSE}")
  DOMAIN_IP=$(jq -r '.[] .record' <<<"${API_RESPONSE}")
  if [[ "${DOMAIN_ID}" == "" ]]; then
    bm_task_skip "IPv6 ${DOMAIN}"
  elif [[ "${USE_IP6}" == "${DOMAIN_IP}" ]]; then
    bm_task_skip "IPv6 ${DOMAIN}"
  else
    API_URL="https://api.cloudns.net/dns/get-dynamic-url.json"
    API_REQUEST="\
    {
      \"sub-auth-id\": \"${CLOUDNS_SUB_AUTH_ID}\",
      \"auth-password\": \"${CLOUDNS_AUTH_PASSWORD}\",
      \"domain-name\": \"${PARENT}\",
      \"record-id\": \"${DOMAIN_ID}\"
    }"
    API_RESPONSE=$(curl -s --request POST -H "Content-Type:application/json" "${API_URL}" --data "${API_REQUEST}")
    UPDATE_URL=$(jq -r '.url' <<<"${API_RESPONSE}")
    if [[ "${UPDATE_URL}" != "" ]]; then
      bm_task_update "IPv6 ${DOMAIN}"
      if ! bm_command_execute "curl -s ${UPDATE_URL}"; then
        bm_task_failed "IPv6 ${DOMAIN}"
      else
        bm_task_ok "IPv6 ${DOMAIN}"
      fi
    else
      bm_task_failed "IPv6 ${DOMAIN}"
    fi
  fi
  unset DOMAIN_ID
  unset DOMAIN_IP
  unset PARENT
done

bm_task_start "Cleaning environment"
unset API_URL
unset CONFIG_FILE
unset CLOUDNS_SUB_AUTH_ID
unset CLOUDNS_AUTH_PASSWORD
unset DOMAIN_FILE
unset DOMAINS
unset USE_IP4
unset USE_IP6
bm_task_ok "Cleaning environment"
printf "\033[0m\n"
